#Actividad 1: Eliminación de Duplicados y Tratamiento de Datos Faltantes

In [ ]:
import pandas as pd

Cargar el conjunto de datos.

In [ ]:
data = "https://docs.google.com/spreadsheets/d/13ufG0CQqpozGhJfh8t3T-01p4lcPPZa26TrrWhQux3c/export?format=xlsx"

In [ ]:
df = pd.read_excel(data)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  1032 non-null   object
 1   Edad    973 non-null    float64
 2   Email   1032 non-null   object
dtypes: float64(1), object(2)
memory usage: 24.3+ KB

In [ ]:
df.head()

                Nombre  Edad                     Email
0         Elonore Over  40.0         eoverh6@ocn.ne.jp
1     Jacquette Gillbe  49.0       jgillbeb8@diigo.com
2  Sheelah Olechnowicz  61.0    solechnowiczch@mlb.com
3       Morris Bilovus  32.0  mbilovus3q@artisteer.com
4          Erda Geipel  60.0      egeipelj5@jalbum.net

=

Identificar y eliminar las filas duplicadas: Usarás técnicas específicas para encontrar y eliminar cualquier registro duplicado que pueda afectar la calidad de tu análisis. No olvides escribir un reporte de los hallazgos y modificaciones.

In [ ]:
df_duplicates = df.duplicated()
df_duplicates

0       False
1       False
2       False
3       False
4       False
        ...
1027    False
1028    False
1029     True
1030    False
1031    False
Length: 1032, dtype: bool

In [ ]:
df_sin_duplicates = df.drop_duplicates()
df_sin_duplicates

                   Nombre  Edad                     Email
0            Elonore Over  40.0         eoverh6@ocn.ne.jp
1        Jacquette Gillbe  49.0       jgillbeb8@diigo.com
2     Sheelah Olechnowicz  61.0    solechnowiczch@mlb.com
3          Morris Bilovus  32.0  mbilovus3q@artisteer.com
4             Erda Geipel  60.0      egeipelj5@jalbum.net
...                   ...   ...                       ...
1026        Brande Sibbet  46.0       bsibbetlb@imgur.com
1027      Olivia Braganca  52.0      obragancaat@ucsd.edu
1028         Leia Duckett  62.0       lduckett2z@java.com
1030         Stanton Lyne  45.0        slyned5@paypal.com
1031    Milissent Clayill  60.0    mclayilln3@nytimes.com

[1000 rows x 3 columns]

In [ ]:
df_sin_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 1031
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  1000 non-null   object
 1   Edad    943 non-null    float64
 2   Email   1000 non-null   object
dtypes: float64(1), object(2)
memory usage: 31.2+ KB

Se encontraron 32 entradas duplicadas que fueron eliminadas

Manejar los datos faltantes en la columna de edad, evaluando cuál es la mejor decisión, considerando que vamos a realizar un análisis enfocado en grupos etarios de los clientes. Evaluar el impacto sobre el análisis si:

1.   Se eliminan las filas que no contienen la edad.
2.   Se completa el dato con la media de la columna

In [ ]:
print(df["Edad"].isnull().sum())
print(df[df.isnull().any(axis=1)])

59
                  Nombre  Edad                           Email
23    Timotheus Meggison   NaN            tmeggisong4@digg.com
32       Dominga Dewdney   NaN            ddewdneyrn@naver.com
44          Peggy Songer   NaN        psongeru@photobucket.com
52        Dewey McCulley   NaN         dmcculleyko@tinypic.com
53          Phil Triggol   NaN         ptriggol2l@redcross.org
74         Lilyan Dulton   NaN            ldulton7e@devhub.com
78       Janina Florence   NaN             jflorencekl@cdc.gov
88             Del Lente   NaN             dlente7m@nature.com
110          Wilone Sked   NaN               wskedg7@intel.com
151        Ronnica Mabey   NaN              rmabey8w@topsy.com
163      Margareta Likly   NaN             mliklyfp@devhub.com
189      Candace Ruperti   NaN             cruperti8t@furl.net
212    Bancroft McVanamy   NaN        bmcvanamy4m@trellian.com
229     Marie-ann Kilius   NaN              mkilius4b@dell.com
252    Veronika McLaggan   NaN            vmclagganq8@ox.ac.uk
261    Caritta Hardwidge   NaN       chardwidgebg@virginia.edu
266       Jolene Laviste   NaN           jlaviste7t@senate.gov
267        Pippo Dagless   NaN          pdaglessh0@tinyurl.com
306   Anthiathia Phorsby   NaN                aphorsbyjl@de.vu
311       Olivette Myall   NaN                omyallp4@mapy.cz
327         Lindy Klebes   NaN        lklebesp@yellowpages.com
361          Kipp Godney   NaN          kgodneyeg@mapquest.com
364        Beale Cabbell   NaN             bcabbellli@ebay.com
368      Chaddie Rylance   NaN        crylance5x@tuttocitta.it
449       Traci Di Boldi   NaN              tdilv@berkeley.edu
469         Fiona Pulham   NaN      fpulhamdz@chronoengine.com
501     Pinchas McOrkill   NaN           pmcorkilleo@google.it
504      Lurleen Sewards   NaN            lsewards20@diigo.com
530    Garrett Antognoni   NaN    gantognonim2@sourceforge.net
550       Cullen Ruzicka   NaN               cruzicka26@ca.gov
568     Selia Lorenzetto   NaN      slorenzettojz@mashable.com
585     Yolane Gracewood   NaN           ygracewoodp6@fema.gov
617          Gail Oxtiby   NaN               goxtibyca@loc.gov
620       Ericka Seagood   NaN        eseagood7h@bigcartel.com
627    Mehetabel Stanger   NaN  mstangergz@creativecommons.org
637        Hussein Niese   NaN               hnieseqe@usda.gov
659      Arlyn Jacobsohn   NaN         ajacobsohn4o@paypal.com
698   Consolata Crommett   NaN             ccrommette6@tiny.cc
759      Kristen Scoates   NaN    kscoates2w@elegantthemes.com
763          Dore Kidson   NaN       dkidsonc5@list-manage.com
767      Kathi Blockwell   NaN            kblockwellb6@usa.gov
775         Shelby Beric   NaN               sbericgv@lulu.com
777         Alwyn Ashall   NaN         aashallmb@blinklist.com
807      Felecia Asquith   NaN          fasquith47@typepad.com
826        Dorelle Jewar   NaN              djewaro2@lycos.com
862      Marleen Stirrip   NaN         mstirripby@mashable.com
874        Birgit Deppen   NaN           bdeppenq5@jiathis.com
906     Rodolph Petracco   NaN          rpetraccokj@tumblr.com
907      Candace Ruperti   NaN             cruperti8t@furl.net
937        Yule Sparwell   NaN             ysparwello8@dot.gov
945       Mallissa Skews   NaN              mskewsq1@yandex.ru
959        Ronnica Mabey   NaN              rmabey8w@topsy.com
961      Roderic Musicka   NaN       rmusickam7@shareasale.com
965      Stirling Tenman   NaN             stenmankw@nymag.com
987       Ethel Crichten   NaN             ecrichtenax@npr.org
989         Shea Lapwood   NaN        slapwoodng@delicious.com
1001      Laureen Mahony   NaN    lmahony6a@huffingtonpost.com
1009       Kamilah Brame   NaN           kbrameni@slashdot.org
1015   Derick Scorthorne   NaN        dscorthornekd@eepurl.com

Se eliminan los registros sin edad para no dificultar el analisis

In [ ]:
df_final = df.dropna(subset=["Edad"])
df_final

                   Nombre  Edad                     Email
0            Elonore Over  40.0         eoverh6@ocn.ne.jp
1        Jacquette Gillbe  49.0       jgillbeb8@diigo.com
2     Sheelah Olechnowicz  61.0    solechnowiczch@mlb.com
3          Morris Bilovus  32.0  mbilovus3q@artisteer.com
4             Erda Geipel  60.0      egeipelj5@jalbum.net
...                   ...   ...                       ...
1027      Olivia Braganca  52.0      obragancaat@ucsd.edu
1028         Leia Duckett  62.0       lduckett2z@java.com
1029     Kaitlynn Sigmund  45.0     ksigmund8e@census.gov
1030         Stanton Lyne  45.0        slyned5@paypal.com
1031    Milissent Clayill  60.0    mclayilln3@nytimes.com

[973 rows x 3 columns]

#Actividad 2: Corrección de Tipos de Datos y Normalización

Cargar el conjunto de datos.

In [ ]:
datos = "https://docs.google.com/spreadsheets/d/170GDFJKpZEaBbA48mII018sW6qBOGz2X4UlV4HNQaWo/export?format=xlsx"

In [ ]:
df_2 = pd.read_excel(datos)

In [ ]:
df_2.info()
df_2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Producto   100 non-null    object
 1   Categoría  100 non-null    object
 2   Precio     100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

    Producto           Categoría  Precio
0      Acero               Metal  $13.54
1  Plexiglás  Polímero/Sintético  $45.10
2      Latón               Metal  $35.64
3    Granito      Piedra Natural  $61.61
4      Acero               Metal  $14.28

Corregir el tipo de datos de la columna de precio a un tipo numérico.

In [ ]:
df_2["Precio"] = df_2["Precio"].str.replace("$", "")

In [ ]:
df_2["Precio"] = df_2["Precio"].astype(float)

In [ ]:
df_2.info()
df_2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Producto   100 non-null    object
 1   Categoría  100 non-null    object
 2   Precio     100 non-null    float64
dtypes: float64(1), object(2)
memory usage: 2.5+ KB

    Producto           Categoría  Precio
0      Acero               Metal   13.54
1  Plexiglás  Polímero/Sintético   45.10
2      Latón               Metal   35.64
3    Granito      Piedra Natural   61.61
4      Acero               Metal   14.28

Normalizar el nombre del producto para que todas las entradas estén en minúsculas y sin caracteres especiales.

In [ ]:
df_2["Producto"] = df_2["Producto"].str.lower()

In [ ]:
df_2.head()

    Producto           Categoría  Precio
0      acero               Metal   13.54
1  plexiglás  Polímero/Sintético   45.10
2      latón               Metal   35.64
3    granito      Piedra Natural   61.61
4      acero               Metal   14.28

In [ ]:
df_2["Producto"] = df_2["Producto"].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
df_2

    Producto           Categoría  Precio
0      acero               Metal   13.54
1   plexigls  Polímero/Sintético   45.10
2       latn               Metal   35.64
3    granito      Piedra Natural   61.61
4      acero               Metal   14.28
..       ...                 ...     ...
95    vidrio              Vidrio   80.31
96   granito      Piedra Natural   10.67
97  plexigls  Polímero/Sintético   59.53
98   plstico  Polímero/Sintético   31.13
99    madera              Madera   56.60

[100 rows x 3 columns]