#Actividad 1

In [ ]:
import pandas as pd

Descargar los datos en formato CSV y cargarlos en un DataFrame en Python usando Pandas.

In [ ]:
pd_actividad_2 = "https://docs.google.com/spreadsheets/d/1BEzV2yb9-7SUgXjRIA0r7YLCWPUH8kAN/export?format=xlsx"

In [ ]:
df = pd.read_excel(pd_actividad_2)

In [ ]:
df.head()

,nombre,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10
0,Marcellus Antosik,36.85,36.01,37.36,37.85,36.31,36.55,36.71,37.79,36.44,36.86
1,Olia Thomson,36.06,36.42,36.16,36.03,36.00,36.08,37.45,37.92,37.53,36.54
2,Almeta Meredith,36.89,37.74,36.16,36.59,37.93,37.12,36.34,36.04,NaN,37.05
3,Massimiliano Waller,36.50,37.91,NaN,36.16,37.41,37.73,36.57,37.94,36.03,36.80
4,Melody Fedynski,37.90,37.69,36.55,37.06,37.81,36.77,36.89,36.35,37.36,37.08

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3018 entries, 0 to 3017
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  3018 non-null   object
 1   d1      2832 non-null   float64
 2   d2      2871 non-null   float64
 3   d3      2822 non-null   float64
 4   d4      2839 non-null   float64
 5   d5      2855 non-null   float64
 6   d6      2820 non-null   float64
 7   d7      2864 non-null   float64
 8   d8      2834 non-null   float64
 9   d9      2816 non-null   float64
 10  d10     2845 non-null   float64
dtypes: float64(10), object(1)
memory usage: 259.5+ KB

In [ ]:
len(df)

3018

Utilizar el método isnull() para identificar las filas con datos faltantes y contar el número de valores nulos por columna.

In [ ]:
df_nulos = df.isnull()
df_nulos

,nombre,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
3013,False,False,False,False,False,False,False,False,False,False,False
3014,False,True,False,False,False,False,False,True,False,False,False
3015,False,False,False,False,False,False,False,False,False,False,False
3016,False,False,False,False,False,False,False,False,False,False,False
3017,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
cant_nulos = df_nulos.sum()
cant_nulos

nombre      0
d1        186
d2        147
d3        196
d4        179
d5        163
d6        198
d7        154
d8        184
d9        202
d10       173
dtype: int64

Usar el método duplicated() para identificar las filas duplicadas y contar cuántas filas duplicadas hay en total.

In [ ]:
df_duplicates = df.duplicated()

In [ ]:
df_duplicates

0       False
1       False
2       False
3       False
4       False
        ...
3013    False
3014    False
3015    False
3016     True
3017    False
Length: 3018, dtype: bool

In [ ]:
cant_duplicates = df_duplicates.sum()
cant_duplicates

np.int64(18)

Crear un informe que incluya:

1.  La cantidad total de registros en el DataFrame.
2.  La cantidad total de valores nulos por columna.
3.  La cantidad de filas duplicadas.

In [ ]:
cant_registros = len(df)
cant_reg_nulos = cant_nulos
cant_reg_dup = cant_duplicates

print(f"""
Informe:

Se observan en el dataframe un total de {cant_registros} registros.

Tiene la siguiente cantidad de registros nulos por columna:\n\n{cant_reg_nulos}

Esta es la cantidad de filas duplicadas: {cant_duplicates}

""")

Informe:

Se observan en el dataframe un total de 3018 registros.

Tiene la siguiente cantidad de registros nulos por columna:

nombre      0
d1        186
d2        147
d3        196
d4        179
d5        163
d6        198
d7        154
d8        184
d9        202
d10       173
dtype: int64

Esta es la cantidad de filas duplicadas: 18

Crear un dataframe de los registros duplicados para que se vea el contenido.

In [ ]:
df_reg_duplicados = df[df.duplicated()]
df_reg_duplicados

,nombre,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10
136,Dagny Burree,37.58,36.17,37.00,37.84,37.29,37.54,36.07,36.75,NaN,36.53
235,Merola Muscat,36.24,37.19,37.16,37.66,36.88,37.80,36.04,37.47,38.00,36.92
847,Bernarr D'Arrigo,36.83,36.94,NaN,36.01,37.80,37.94,36.30,37.97,37.75,37.35
1413,Pascal Merfin,37.14,36.31,37.61,37.12,37.28,36.43,37.39,36.69,37.83,37.17
1414,Marijn Lothean,37.89,37.06,37.05,37.05,37.32,37.78,36.97,37.84,37.62,37.78
1451,Gerladina Maguire,36.60,36.69,37.69,37.17,36.57,37.29,36.01,36.52,37.73,36.26
1528,Andriana Mossman,37.40,36.81,37.46,36.89,36.22,36.40,37.97,36.07,37.86,NaN
1687,Ginger Iacoviello,36.06,37.71,36.05,36.88,NaN,36.37,37.15,36.90,37.03,37.61
2200,Ailyn Hexter,36.67,36.10,36.36,36.59,36.99,37.22,36.34,37.51,36.72,37.59
2261,Winne Margiotta,37.84,37.40,37.23,37.90,NaN,NaN,37.01,37.03,36.84,37.53
2456,Dennison Vanyashkin,36.67,36.47,36.41,37.09,36.86,36.48,36.01,37.86,36.99,36.10
2461,Holden Kerry,36.07,37.11,36.58,NaN,36.41,36.63,36.60,36.70,36.51,37.53
2525,Read Wemyss,36.79,36.00,37.50,36.82,37.13,37.94,37.63,37.81,37.71,37.28
2629,Hamlin Denial,36.62,37.66,37.99,NaN,NaN,36.01,37.32,36.71,36.47,37.43
2668,Sal Oury,36.77,36.51,36.51,36.56,36.60,36.30,37.26,37.12,37.60,36.90
2954,Celeste Gooch,36.11,36.87,36.68,NaN,37.92,36.72,37.93,37.29,36.15,36.60
2991,Paige Catherine,37.55,36.08,37.17,36.72,36.01,36.42,37.97,37.66,36.12,37.77
3016,Hoyt Koenen,37.57,37.23,36.76,36.17,36.61,37.21,37.66,37.18,36.45,36.68

#Actividad 2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3018 entries, 0 to 3017
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  3018 non-null   object
 1   d1      2832 non-null   float64
 2   d2      2871 non-null   float64
 3   d3      2822 non-null   float64
 4   d4      2839 non-null   float64
 5   d5      2855 non-null   float64
 6   d6      2820 non-null   float64
 7   d7      2864 non-null   float64
 8   d8      2834 non-null   float64
 9   d9      2816 non-null   float64
 10  d10     2845 non-null   float64
dtypes: float64(10), object(1)
memory usage: 259.5+ KB

In [ ]:
valores_fuera_de_rango = df[df["d10"] > 45]
print(valores_fuera_de_rango)

Empty DataFrame
Columns: [nombre, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10]
Index: []

In [ ]:
minimos = df.min()
minimos

nombre    Aarika Jaze
d1               36.0
d2               36.0
d3               36.0
d4              36.01
d5               36.0
d6               36.0
d7               36.0
d8               36.0
d9               36.0
d10              36.0
dtype: object

In [ ]:
maximos = df.max()
maximos

nombre    Zorina Leall
d1                38.0
d2                38.0
d3                38.0
d4                38.0
d5                38.0
d6                38.0
d7                38.0
d8                38.0
d9                38.0
d10               38.0
dtype: object

# Recomendaciones para el analisis:
## Para el estudio estadistico
* Datos anomalos: No existen casos anomalos.
* Datos nulos: rellenar con la media de cada fila.

## Seguimiento de un paciente
* Datos anómalos: no se encontraron.
* Datos nulos: ignorar los datos.

## Detección de casos de contagio
* Datos anómalos: realizar un analisis más profundo de estos casos, examinar si los datos se repiten en la misma persona multipleces veces. Y si se repiten con multiples personas.
* Datos nulos: ignorar a menos que se conozca si la persona se contagio, en ese caso rellenar con la media.